drop table plugins.fundamentacaolegal;
drop sequence plugins.fundamentacaolegal_sequencial_seq;
drop table plugins.fundamentacaolegaldesdobramentos;
drop sequence plugins.fundamentacaolegaldesdobramentos_sequencial_seq;
drop table plugins.empautorizafundamentacaolegal;
drop sequence plugins.empautorizafundamentacaolegal_sequencial_seq;
drop table plugins.fundamentacaolegalmodalidade;
drop sequence plugins.fundamentacaolegalmodalidade_sequencial_seq;